version: "3.2"
services:
  web:
    image: mmandaglio/citesteo
    build:
      cache_from:
        - mmandaglio/citesteo
      context: .
    depends_on:
      - redis
    ports:
      - 5000:5000
  redis:
    image: redis
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes: 
      - .:/ci
    depends_on:
      - web
    command: sh /ci/test.sh
